[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["ctrlaltf2 <23644849+ctrlaltf2@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
